### ISSUE TITLE
Deal with cases where there are more than two alternatives

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/regovar-server#12]
and not only compound heterozygous.

![alt infini](https://cloud.githubusercontent.com/assets/5510283/23222975/f49b8aca-f929-11e6-926a-4fb44f693a54.png)

**Comment by ikit** [comment]
Alt1/alt2 doesn't  means that the variant have the alt number 1 in the imported VCF and the alt number 2 in the vcf. it means that it's a variant "hetero alt" with 2 disctinct alt. by opposition to a variant hetero alt with one ref and one alt. You see what I mean ?

Once variant are imported in annso database, they are not more ordered as in the vcf row...
This enum just describe all possibility for the variant's genotype.
