### ISSUE TITLE
Errors while initialising the database

### ISSUE THREAD

**Issue by Jnsll** [REGOVAR/regovar-server#14]
At the step 'Init database' in the Quick guide, when i run `psql -U annso -d annso -f <ANNSO_PATH>/annso/database/create_all.sql` several errors happen.
The message i get is in the linked framapad. 

I guess there's something wrong with the UTF8 encoding ?

[framapad : error_init_db](https://mypads.framapad.org/mypads/?/mypads/group/projects-wv2sx7zc/pad/view/error-init-db-annso-jt2tx7zd)

**Comment by Jnsll** [comment]
After replacing `C.UTF-8` by `C` in the file <ANNSO_PATH>/annso/database/create_all.sql, i run successively `psql -U annso -d annso -f <ANNSO_PATH>/annso/database/create_all.sql`, `psql -U annso -d annso -f <ANNSO_PATH>/annso/database/scripts/import_refgen.sql` and `make app`.
I still have some errors... 
I have put the errors i got in the following framapad : https://mypads.framapad.org/mypads/?/mypads/group/projects-wv2sx7zc/pad/view/import-refgen-4bdm57f8

**Comment by Arkanosis** [comment]
Regarding the “ /usr/share/postgresql/extension/uuid-ossp.control not found” errors, you probably need to install the `postgresql-contrib` package provided by your operating system in addition to the base `postgresql` package.

**Comment by Arkanosis** [comment]
Regarding the python errors when doing `make app`, are you in the right virtualenv?

I suppose that having done the following:

    virtualenv -p /usr/bin/python3.5 venv
    source venv/bin/activate
    pip install -r requirements.txt

should be enough to have the `aiohttp_jinja2` module available.

**Comment by Arkanosis** [comment]
Issues on Ubuntu Xenial:

    psql -U annso -d annso -f ./annso/database/create_all.sql
    psql:./annso/database/create_all.sql:315: NOTICE:  index "sample_idx" does not exist, skipping
    psql:./annso/database/create_all.sql:324: NOTICE:  index "sample_variant_hg19_idx_id" does not exist, skipping
    psql:./annso/database/create_all.sql:330: NOTICE:  index "sample_variant_hg19_idx_samplevar" does not exist, skipping
    psql:./annso/database/create_all.sql:336: NOTICE:  index "sample_variant_hg19_idx_site" does not exist, skipping
    psql:./annso/database/create_all.sql:343: NOTICE:  index "attribute_idx" does not exist, skipping
    psql:./annso/database/create_all.sql:352: NOTICE:  index "variant_hg19_idx_id" does not exist, skipping
    psql:./annso/database/create_all.sql:358: NOTICE:  index "variant_hg19_idx_site" does not exist, skipping
    psql:./annso/database/create_all.sql:365: NOTICE:  index "analysis_idx" does not exist, skipping
    psql:./annso/database/create_all.sql:374: NOTICE:  index "filter_idx" does not exist, skipping
    psql:./annso/database/create_all.sql:382: NOTICE:  index "annotation_database_idx" does not exist, skipping
    psql:./annso/database/create_all.sql:387: NOTICE:  index "annotation_database_idx2" does not exist, skipping
    psql:./annso/database/create_all.sql:392: NOTICE:  index "annotation_field_idx" does not exist, skipping
    psql:./annso/database/create_all.sql:397: NOTICE:  index "annotation_field_idx2" does not exist, skipping
    psql:./annso/database/create_all.sql:417: NOTICE:  extension "uuid-ossp" already exists, skipping
    psql:./annso/database/create_all.sql:516: ERROR:  syntax error at or near "CREATE"
    LINE 6: CREATE OR REPLACE FUNCTION array_intersect(anyarray, anyarra...
            ^
    psql:./annso/database/create_all.sql:543: ERROR:  syntax error at or near "CREATE"
    LINE 16: CREATE OR REPLACE FUNCTION array_search(needle ANYELEMENT, h...
             ^

And then:

    psql -U annso -d annso -f ./annso/database/scripts/import_refgen.sql
    psql:./annso/database/scripts/import_refgen.sql:7: NOTICE:  table "import_refgene_hg19" does not exist, skipping
    psql:./annso/database/scripts/import_refgen.sql:34: ERROR:  could not open file "/var/regovar/data/db/refgen/refGene.txt" for reading: No such file or directory
    psql:./annso/database/scripts/import_refgen.sql:47: NOTICE:  table "refgene_hg19" does not exist, skipping
    psql:./annso/database/scripts/import_refgen.sql:74: NOTICE:  table "refgene_exon_hg19" does not exist, skipping
    psql:./annso/database/scripts/import_refgen.sql:156: ERROR:  function array_search(character varying, character varying[]) does not exist
    LINE 5:   exonpos  =array_search(CAST(i_exonstart AS character varyi...
                        ^
    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
    psql:./annso/database/scripts/import_refgen.sql:187: NOTICE:  index "refgene_hg19_chrom_txrange_idx" does not exist, skipping
    psql:./annso/database/scripts/import_refgen.sql:193: NOTICE:  index "refgene_hg19_txrange_idx" does not exist, skipping
    psql:./annso/database/scripts/import_refgen.sql:201: NOTICE:  index "refgene_exon_hg19_chrom_exonange_idx" does not exist, skipping
    psql:./annso/database/scripts/import_refgen.sql:207: NOTICE:  index "refgene_exon_hg19_exonange_idx" does not exist, skipping

**Comment by ikit** [comment]
@Arkanosis : On your server, do you also have the problem with "C" vs "C.UTF-8" collation ?

**Comment by Arkanosis** [comment]
At least not on Ubuntu; I haven't tested on Debian / ArchLinux yet. Not sure whether the issue there is on our side. I'll dig further into it later.

**Comment by Jnsll** [comment]
> Regarding the python errors when doing make app, are you in the right virtualenv?

We're right ! I wasn't in the virtualenv that time.. I don't have the aiohttp_jinja2 error anymore but I still have the following one when running `make app`
```
make app
python annso_server.py
2017-03-13 19:41:46,747 | # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
Traceback (most recent call last):
  File "annso_server.py", line 16, in <module>
    raise AnnsoException("ERROR : Cache directory doesn't exists : " + CACHE_DIR)
core.framework.AnnsoException: [ERROR:00000] 0ba54d40-7ddf-429d-9db2-d968bac9b7af : Unknow error :/

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

make: *** [Makefile:11: app] Error 1

```

**Comment by Arkanosis** [comment]
@ikit  No more SQL errors for me on Ubuntu (notices are still present, but that's not really an issue).

**Comment by Arkanosis** [comment]
@JuneBS Have a look at #16 : there were some inconsistencies between the current version of the code and the documentation. It's being fixed soon!
NB: if you're installing on bare metal, just ignore the lxc-* stuff.

**Comment by ikit** [comment]
@JuneBS : before running the application, you must create several directories. throw an eye to the config.py file.
If you didn't change default value you should have to create :
mkdir -p /tmp/annso_v1/{cache,downloads,files}

But it's a wrong idea to put them in the /tmp/ directory, as this directory is empty each time you reboot your computer/server/. So I think you should create theses directories in /var/regovar/annso by example, and update the config.py file accordingly.

**Comment by Jnsll** [comment]
@ikit Yep, you're right. I've git pulled the new changes and have not checked the config.py again before running the `make app` command. Sorry. 
With creating the right folders (`/var/regovar/annso/`), it worked. I was getting the #15 but changed the host to `HOST = "0.0.0.0"` and it worked.
