### ISSUE TITLE
Hardcoded references to absolumentg.fr

### ISSUE THREAD

**Issue by Arkanosis** [REGOVAR/regovar-server#15]
$ grep absolumentg -R .
    ./annso/reports/dims/report.html:    <script type="text/javascript" src="https://annso.absolumentg.fr/v1/cache/reports/dims/common.js"></script>
    ./annso/reports/dims/report.html:        <li><img src="https://annso.absolumentg.fr/v1/cache/reports/dims/hbt_image_{{gene.name}}.png" title="HBT" style="max-width: 700px;"/></li>
    ./annso/reports/dims/report.html:    <img src="https://annso.absolumentg.fr/v1/cache/reports/dims/decipher_image_{{gene.name}}.png" title="Decipher snapshot" style="max-width: 700px;"/><br/>
    ./annso/reports/dims/report.html:    <img src="https://annso.absolumentg.fr/v1/cache/reports/dims/sp_image_{{gene.name}}.png" title="String pathway snapshot" style="max-width: 700px;"/><br/>
    ./annso/config.py:HOST_P = "annso.absolumentg.fr/" + VERSION

Wouldn't relative URLs (for HTML / JS) and `localhost` (for Python) do the trick?

**Comment by Oodnadatta** [comment]
![screenshot_20170313_003641](https://cloud.githubusercontent.com/assets/5510283/23837231/4df67576-0785-11e7-865b-c298395474dd.png)
I have a local install of Annso but the websocket requests still target absolumentg.fr.

**Comment by Oodnadatta** [comment]
When I replace `absolumentg.fr` with `/` in the `config.py` file, I get a network error.

**Comment by ikit** [comment]
@Oodnadatta : you have to set the hostname with a network url. Instead of "/" can you test you "0.0.0.0", "127.0.0.1" or "localhost" or something like that ?

**Comment by Jnsll** [comment]
With changing the host address to `HOST = "0.0.0.0"` in the `config.py` file, I don't have the hardcoded reference problem to absolumentg.fr for the websocket requests anymore. 
![nomore_hardcoded_ref](https://cloud.githubusercontent.com/assets/15047775/23875096/7bdf4a18-0838-11e7-8174-2e81163dbd85.png)
